### ISSUE TITLE
Add functionality to clean workflow outputs

### ISSUE THREAD

**Issue by ekatef** [pypsa-meets-earth/pypsa-distribution#14]
Thank you for the great package :)

## Describe the feature you'd like to see

When playing with the model, it feels like it may be a good idea to have an opportunity to quickly clean-up all the workflow output to prepare the model to the next run.

Implementation may be as easy as `snakemake -j 1 solve_all_networks --delete-all-output` added to README, or adding a [clean](url) rule like it's done in pypsa-earth.

Happy to open a PR on that, if you think it could be useful :)

**Comment by TomFer97** [comment]
Completely agree
